### ISSUE TITLE
Can't "eat" fold core in creative mode

### ISSUE THREAD

**Issue by TheDeviantCrafter** [TeamDman/Ender-Folds#2]
In survival mode, holding right click causes you to break off a piece of the fold core. This doesn't work in creative mode.

**Comment by TeamDman** [comment]
https://github.com/TeamDman/Ender-Folds/issues/3
https://github.com/TeamDman/Ender-Folds/issues/4
Fixed and pushed to CurseForge

Sorry for the delay!
