### ISSUE TITLE
Only one Fold Core can be extracted per core when "indestructibleDestinations" is set to true

### ISSUE THREAD

**Issue by TheDeviantCrafter** [TeamDman/Ender-Folds#4]
This didn't seem to be an issue before I changed the setting to true. Once a Fold Destination is placed, I can only extract a core once. Quitting the singleplayer game and coming back doesn't reset it.

**Comment by TeamDman** [comment]
Was intended as a primitive security mechanic, but there's definitely a better way it can be implemented.
Not sure why the indestructible setting affected it, it was intended to be one core per destination. Will look into changing it to be more intuitive

**Comment by TheDeviantCrafter** [comment]
I'd like to be able to disable the security mechanic. In my use case, destinations will only exist in naturally generating structures. They're going to be a sort of public resource.

Plus, most packs have some sort of land claiming these days. I don't think security is necessary.
